### ISSUE TITLE
Example .exe download fails

### ISSUE THREAD

**Issue by chrisjj** [eclipse-theia/theia-example#1]
"[Set up CI system to create desktop installer of vanilla Theia #5481](https://github.com/eclipse-theia/theia/issues/5481)" says

> First releases of theia-example v1.2.0 are now appearing here:
> https://download.eclipse.org/theia/

That offers

https://download.eclipse.org/theia/snapshots/windows/theia-Installer-1.2.0.exe

which here (Chrome browser) fails giving "Access Forbidden".

Note: I would contribute this report on the issue itself except someone has locked that issue to non-"contributors" (as if testers aren't contributors) with "Pestering the project for one's pet feature is not productive."

**Comment by vince-fugnitto** [comment]
@thegecko it looks like the download links for the `linux appImage` and `windows exe` do not work at the moment, so it's just a heads up for now.

**Comment by thegecko** [comment]
Thanks for highlighting it, it's probably a file permission setting I need to change before uploading the installers.

**Comment by thegecko** [comment]
Umm, I just tried this myself and can download the files fine.

@chrisjj @vince-fugnitto Can you confirm your experiences?

**Comment by chrisjj** [comment]
> > non-"contributors"
> 
> non-[committers](https://www.eclipse.org/membership/become_a_member/committer.php).

Thanks for the correction.

**Comment by chrisjj** [comment]
> Umm, I just tried this myself and can download the files fine.
> 
> @chrisjj @vince-fugnitto Can you confirm your experiences?

Today it downloads fine. Perhaps someone fixed the permission.

**Comment by thegecko** [comment]
Nothing has changed. Feel free to reopen this issue if there are further problems.

**Comment by chrisjj** [comment]
Caching etc. means we never really know "nothing has changed".
