### ISSUE TITLE
Design about dialog

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-example#10]
Design a proper about dialog with some text describing the purpose of the product (Blueprint product) and pointers to more information:

- Link to download page
- Link to Github project
- Link to report bugs
- Legal information and licenses.

Some graphics would make this dialog more appealing.

For reference this is the default about dialog:

![image2](https://user-images.githubusercontent.com/1044916/100395196-50688780-3040-11eb-9bd2-4cc6ceb99110.png)

**Comment by koegel** [comment]
We (EclipseSource) intend to work on the implementation of this on behalf of ST Microelectronics. Help for the design wanted.

**Comment by koegel** [comment]
We are currently designing an about dialiog.

**Comment by jfaltermeier** [comment]
The current design may look like this:
![ksnip_20210118-105947](https://user-images.githubusercontent.com/5889696/104903875-d8a04480-5980-11eb-9784-819d0bf1128f.png)

**Comment by brianking** [comment]
Does a document exist with the content? Would you like content to worked on in this issue, or in a separate one?

cc @croundy

**Comment by koegel** [comment]
We have already transferred the document into [this PR](https://github.com/eclipse-theia/theia-example/pull/24). For improvements I suggest to open a new bug and describe the improvements there or even better to open a PR once the changes of the current PR are merged.

**Comment by meKokabi** [comment]
Please find attached the Download Page Design:
<img width="792" alt="C2" src="https://user-images.githubusercontent.com/75500459/106298850-6f42f000-6222-11eb-9218-d0c99105fe31.png">
<img width="788" alt="C1" src="https://user-images.githubusercontent.com/75500459/106298854-6f42f000-6222-11eb-95a1-8175263517e1.png">

**Comment by koegel** [comment]
Thanks, I guess this is the design for about dialog not for download page, right?

**Comment by koegel** [comment]
DISLAIMER: Personal opinion ahead :)
First proposal: The graphic to me looks like a "digital product" stock photo which I cannot relate to Theia Blueprint
Second proposal: I can see the relation to the Theia logo but it looks a bit "shredded" to me
Both proposals: The font of "Theia" and maybe also "Blueprint" should match the font of "Theia" in the original logo.
I cannot really commit to any of the proposals, but I guess there is other opinions? 

@jfaltermeier @JonasHelming @lucas-koehler What do you think?

**Comment by koegel** [comment]
Also: This issue is closed so please open a new issue with the proposals, e.g. "Improve about dialog"

**Comment by meKokabi** [comment]
That's right! Sorry for confusion!

**Comment by koegel** [comment]
Any further improvement efforts by @meKokabi are now pursued in #11
