### ISSUE TITLE
Define Release process for installer

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-example#12]
Define how and when to release a new version of the installer and how this process is related to the Theia release process.

**Comment by koegel** [comment]
We (EclipseSource) intend to work on this on behalf of ST Microelectronics.

**Comment by koegel** [comment]
We would like to make the following proposals, open for discussion, of course:

Release frequency: Once every quarter about 2 weeks after Theia release.
For example if Theia is released end of February a blueprint product version should become available mid of March.

Versioning: The installer always has the major version and minor version of the underlying Theia release. It might differ in the patch version in case the installer needs fixes for the same Theia version. The idea of this is to make it clear which version of Theia is contained in the Blueprint product. 

Publishing process: Do not publish automatically from Master but only on an explicit trigger to avoid accidentally publishing changes, e.g. to the updater. Update download page manually to point to current release.

**Comment by koegel** [comment]
@thegecko: What do you think?

**Comment by thegecko** [comment]
> Release frequency: Once every quarter about 2 weeks after Theia release.

My concern here is how quickly Theia is being developed, it could take 3 Months for a feature to appear in the installers.

Is the proposed release cadence less frequent due to the overhead of doing it?

Apart from that it looks sensible.

**Comment by koegel** [comment]
> My concern here is how quickly Theia is being developed, it could take 3 Months for a feature to appear in the installers.
I agree this might be a concern. My view on this depends on what we want the product to be. If it is a blueprint for showing how to build Theia-based products (current scope to my understanding) then it is imho not that important to have all the current features as long as the setup still works. If we intend to build a VS Code alternative then it is very important to have all the latest features. 
In any way we can change the release frequency at any point in time it is not cast in stone, our main idea was to limit the overhead.

**Comment by koegel** [comment]
@thegecko OK, we are all set then, @jfaltermeier will take care to trigger the release in time, we can close this issue imho.
