### ISSUE TITLE
Define name for the Theia installer blue print product

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-theia/theia-example#19]
The name should indicate that the downloadable product is blue print/reference product to showcase the capabilities of Eclipse Theia. As a blue print product that serves two purposes:
1. A template to build custom products based on Theia (including an installer)
2. An easy way to consume the latest state of Theia as a desktop application (including an installer)

To indicate the purpose in the name, we suggest to use
Full name: "Eclipse Theia Blue Print Product"
Shorter: "Eclipse Theia Blue Print"
Even Shorter: "Theia BP"

**Comment by JonasHelming** [comment]
We (EclipseSource) intend to contribute to this on behalf of ST Microelectronics.

@koegel

**Comment by koegel** [comment]
I also discussed this with the Theia team in a call last year and their intention is to clearly state that this is (at least for now) not intended to be THE Theia product and also not intended to be a replacement for VS Code but rather an example product to showcase the capabilities of the Theia platform. Our team also agrees with this. We believe it is important to manage expectations, for an example see [here](https://github.com/eclipse-theia/theia/issues/8707#issuecomment-752287123).

Therefore we will go with the following name:
Full name: "Eclipse Theia Blueprint Product"
Short name: "Theia Blueprint"

**Comment by marcdumais-work** [comment]
An additional related thing to do would be to use the chosen name in the app's `package.json` and in other relevant places. An important one is to use a custom "user level" configuration folder - ATM it uses the same we use for `theia` development, `<user's home>/.theia`.

**Comment by marcdumais-work** [comment]
see: https://github.com/eclipse-theia/theia-example/blob/master/electron-app/scripts/theia-electron-main.js#L9 : 
```javascript
process.env.THEIA_PLUGINS = [
    process.env.THEIA_PLUGINS, `local-dir:${path.resolve(os.homedir(), '.theia', 'plugins')}`,
].filter(Boolean).join(',')
```

**Comment by koegel** [comment]
Very good points, thank you! I opened an issue to track this, see #25

**Comment by brianking** [comment]
At the Foundation a couple of weeks back we ideated on some names and ran them by @JonasHelming. Ultimately the decision was made to continue using Blueprint.

cc @croundy

**Comment by koegel** [comment]
OK, I think this ticket can be considered done, @JonasHelming Can you please close it.
