### ISSUE TITLE
Add welcome page in instance

### ISSUE THREAD

**Issue by koegel** [eclipse-theia/theia-example#9]
Design a welcome page describing the purpose of the blueprint and some details:
- How to get the source code and/or contribute
- How to report bugs
- Quick intro to included functionality potentially with links to the functionality

Some image to make it less boring, e.g. half-transparent Theia logo in the background
From a technical perspective we have no limitations of how this may be customized. 
For reference, this is the default welcome page / getting started:

![image1](https://user-images.githubusercontent.com/1044916/100395040-9a9d3900-303f-11eb-8e78-98cd03241950.png)

**Comment by koegel** [comment]
We (EclipseSource) intend to work on implementing this on behalf of ST Microelectronics. Help with the design wanted.

**Comment by koegel** [comment]
We are currently defining a welcome page.

**Comment by jfaltermeier** [comment]
The current design may look like this:
![ksnip_20210118-105935](https://user-images.githubusercontent.com/5889696/104903813-c6bea180-5980-11eb-95a5-160e80214c60.png)

**Comment by marcdumais-work** [comment]
@vince-fugnitto I think you've made the default framework welcome page - you might have feedback for the proposal here?

**Comment by brianking** [comment]
Does a document exist with the content for the Welcome page? Would you like content to worked on in this issue, or in a separate one?

cc @croundy

**Comment by koegel** [comment]
We have already transferred the document into [this PR](https://github.com/eclipse-theia/theia-example/pull/24). For improvements I suggest to open a new bug and describe the improvements there or even better to open a PR once the changes of the current PR are merged.

**Comment by brianking** [comment]
Thanks @koegel. We are more comfortable working in G Docs, so we'll pull the content out of here into a doc, make updates, and then bring it back here via a PR.

**Comment by meKokabi** [comment]
Please find attached the welcome page design ( 3 options) 
**Design Concept: Binary Codes - Broad Capabilities - Modern - Agile- Referencing Theia logo visual elements - Minimal - Bold**

<img width="769" alt="2A" src="https://user-images.githubusercontent.com/75500459/106297937-453cfe00-6221-11eb-9290-4cce39048598.png">
<img width="787" alt="Screen Shot 2021-01-29 at 8 08 13 AM" src="https://user-images.githubusercontent.com/75500459/106297941-466e2b00-6221-11eb-8be2-ad947c6c8d79.png">
<img width="769" alt="!A" src="https://user-images.githubusercontent.com/75500459/106297949-48d08500-6221-11eb-8557-49612be65c53.png">

**Comment by MatthewKhouzam** [comment]
None of my business, is that the "oracle" font? are we allowed to use it?

**Comment by koegel** [comment]
DISLAIMER: Personal opinion ahead :)
First proposal: Looks OK to me, but I am not sure if it will look good with all the text on the graphic, since there is a lot of text, see screenshot of Johannes above.
Second proposal: The graphic to me looks like a "broadband" stock photo which I cannot relate to Theia Blueprint
Third  proposal: The graphic to me looks like a "digital product" stock photo which I cannot relate to Theia Blueprint

All proposals: The font of "Theia" and maybe also "Blueprint" should match the font of "Theia" in the original logo. Also for all proposals I would like to see how they look like within the Theia frame and with all the text on top as shown in the screenshot of Johannes above. 

I cannot really commit to any of the proposals, but I guess there is other opinions?

@jfaltermeier @JonasHelming @lucas-koehler What do you think?

**Comment by koegel** [comment]
Also: This issue is closed so please open a new issue with the proposals, e.g. "Improve welcome page design"

**Comment by vince-fugnitto** [comment]
@koegel @meKokabi what types of improvements were we thinking of including to the current welcome page design (besides possibly responsiveness)? I'm not sure that the proposals are improvements over #24, in fact the new proposals have less information and are rather unclear. We need to keep in mind that this is the first page users/adopters will see,  I'm not sure using stock images or graphics without a clear purpose is the best way forward, or gives a professional product feeling.

**Comment by JonasHelming** [comment]
I actually share the main point the @vince-fugnitto is raising. I think it will be difficult to provide the information we want on with a lot of graphics in the background. Looking at any other IDE such as Eclipse, IntelliJ or VS Code, they all focus on simplicity, important information and first steps on their welcom page. Speaking of which, I opened https://github.com/eclipse-theia/theia-example/issues/30 as a potential future imporvement, basically the idea to re-add some of the action that the default page had, such as "recent workpaces". My personal answer to Vince's question would be that for future revisions on this we should focus on displaying the right information in the most comprehensible way possible and keep it visually clean.

**Comment by koegel** [comment]
Any further improvement efforts by @meKokabi are now pursued in #11. I have made a proposal on how to continue addressing the comments of @vince-fugnitto and @JonasHelming on #11. Please comment on my proposal there.

**Comment by koegel** [comment]
> @koegel @meKokabi what types of improvements were we thinking of including to the current welcome page design (besides possibly responsiveness)? I'm not sure that the proposals are improvements over #24, in fact the new proposals have less information and are rather unclear. We need to keep in mind that this is the first page users/adopters will see, I'm not sure using stock images or graphics without a clear purpose is the best way forward, or gives a professional product feeling.

Responsiveness and some other minor improvements are already tracked in #27. Also I fully agree with your assessment that this does not further improve the existing design. I therefore proposed a different approach in #11.
